---
title: "5_Linear_Models"
author: "C.M. Gienger"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ggfortify)
library(emmeans)
library(multcomp)
```
## General Introduction to Linear Models
Need to parse out to separate code chunks
```{r plant growth}
plant_gr <- read.csv("plant.growth.rate.csv")
```

```{r}
glimpse(plant_gr)
```

```{r}
#as always, make a plot first
ggplot(plant_gr,
       aes(x = soil.moisture.content, y = plant.growth.rate)) +
  geom_point() +
  ylab("Plant Growth Rate (mm/week)") +
  theme_bw()
```

```{r}
#fit the model; notice y variable define first, "as function of..."
model_pgr <- lm(plant.growth.rate ~ soil.moisture.content,
                data = plant_gr)
```

```{r message=FALSE, warning=FALSE}
#check the assumptions
autoplot(model_pgr, smooth.colour = NA)
```

```{r}
#interpret the model
anova(model_pgr) #does not perform ANOVA
summary(model_pgr)
```

```{r}
#add model prediction from coefficients (fit line) to the graph 
ggplot(plant_gr, aes(x = soil.moisture.content,
                     y = plant.growth.rate)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  ylab("Plant Growth Rate (mm/week)") +
  theme_bw()
```

**One-Way Analysis of Variance (ANOVA)**

```{r}
daphnia <- read.csv("Daphniagrowth.csv")
```

```{r}
glimpse(daphnia)
```

```{r}
#first we plot the data; boxplots are good for categorical predictors
ggplot(daphnia, aes(x = parasite, y = growth.rate)) +
  geom_boxplot() +
  theme_bw()
```

```{r}
#flip axes so labels are not smashed
ggplot(daphnia, aes(x = parasite, y = growth.rate)) +
  geom_boxplot() +
  theme_bw() +
  coord_flip()
```

```{r}
#construct linear model-check assumptions
model_grow <- lm(growth.rate ~ parasite, data = daphnia)
```

```{r message=FALSE, warning=FALSE}
autoplot(model_grow, smooth.colour = NA)
```

```{r}
#evaluate the linear model
anova(model_grow)
```

```{r}
#treatment contrasts (pairwise comparisons)
summary(model_grow)
```

```{r}
#recall calculating means using dplyr
# get the mean growth rates
sumDat<-daphnia %>%
  group_by(parasite) %>%
  summarise(meanGR = mean(growth.rate))
sumDat
```

```{r}
#Multiple Contrasts using EMmeans package
emm_model_grow<- emmeans(model_grow, "parasite")
pairs(emm_model_grow)
```

```{r}
#visually compare marginal means (LS means)
plot(emm_model_grow, comparisons = TRUE)+
  coord_flip()
```

```{r}
#connecting letters differences report
multcomp::cld(emm_model_grow)
```

